### ISSUE TITLE
Install via pip of murmurhash==1.0.1 fails in Alpine linux, works in Mac OSX

### ISSUE THREAD

**Issue by akilman** [explosion/murmurhash#11]
I'm able to install `murmurhash==1.0.1` no problem in OSX (Mojave). However, in my Docker container, its a no-go. From the logs, I'd wager this distribution isn't available for this architecture. 

The container image is based on `python:alpine`

Here are the relevant logs noted below:
```
No matching distribution found for murmurhash==1.0.1
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 245, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/index.py", line 533, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for murmurhash==1.0.1
```

**Comment by akilman** [comment]
For context, this was happening in installing `spacy` which required `murmurhash`. Turns out, there was a bit of flexibility in what version of `murmurhash` to use. As a workaround, I explicitly installed `1.0.0`, and my build completed without error.

**Comment by maxcountryman** [comment]
I'm running into the same issue: it seems like the package is not available somehow.

**Comment by akilman** [comment]
The following repository has a repro of the issue: https://github.com/akilman/spacy-docker

```bash
docker build -t spacy-docker .
```

**Comment by honnibal** [comment]
Huh, it turns out the sdist didn't get uploaded for murmurhash v1.0.1 -- only the wheels. Should be fixed now, thanks.

Btw, any idea why the wheels won't install for your docker container?

**Comment by akilman** [comment]
@honnibal thanks for the reply.

On why the wheels won't install, I am not sure. If there's some specific info from my environment I can relay, happy to facilitate.
